FROM public.ecr.aws/lambda/python:3.11

COPY models/ ${LAMBDA_TASK_ROOT}/models/

COPY requirements.lambda.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY ./src/lambda_function.py ${LAMBDA_TASK_ROOT}/lambda_function.py